spring:
   application:
      name: DateUtilApp
      
api:
  day:
  #1000 * 60 * 60 * 24 - day calculation in millis
    millis: ${one_day_millis:86400000} 
  date:
    format: ${dt_format:dd/MM/yyyy}
    regex: ^(3[01]|[12][0-9]|0[1-9])/(1[0-2]|0[1-9])/[0-9]{4}$